#!/usr/bin/env python
# coding: utf-8

"""
This is only a script to test the module: PlotHeatmap

"""


import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import PlotHeatmap

# Plot data, read csv file
print('PlotHeatmap, using CSV data')
PlotHeatmap.main(
{ 
    'data_import_type'  : 'CSV', # Test|DataFrame|CSV
    'picture_filename'  : 'doc/mypic_testfile_csv',
    'csv_filename'      : 'doc/test_missing_files.csv',
    'data_source'       : '/datsource/csv',
    '_optional_info'    : {
        'description'   : 'description of the dataset',
        'keyword'       : 'keyword of dataset CSV'
    }
}
)

# Plot data, data generated by module
print('PlotHeatmap, using local defined data')
PlotHeatmap.main(
{ 
    'data_import_type'  : 'Test', # Test|DataFrame|CSV
    'picture_filename'  : 'doc/mypic_local_dataframe',
    'data_source'       : '/datsource/localdataframe',
      '_optional_info'    : {
        'description'   : 'description of the dataset',
        'keyword'       : 'keyword of dataset Test'
    }
}
)



# create panda date range: dtype: datetime64[ns]
date_rng = pd.date_range(start='3/19/2019', end='8/26/2019', freq='12H')

# create DataFrame
df = pd.DataFrame(date_rng, columns=['date']) # dtype: datetime64[ns]

df['missing files'] = np.random.randint(0,3,size=(len(date_rng)))


# add a data element
ts = pd.to_datetime("2019-03-10 18:47:05.487", format="%Y-%m-%d %H:%M:%S.%f")
df =df.append({'date' : ts , 'missing files' : 2},ignore_index=True)

# sort data
df = df.sort_index(ascending=1)




# Plot data, data = DataFrame
print('PlotHeatmap, using data from DataFrame')
PlotHeatmap.main(
{ 
    'data_import_type'  : 'DataFrame', # Test|DataFrame|CSV
    'picture_filename'  : 'doc/mypic_external_dataframe',
    #'csv_filename'     : 'test_missing_files.csv',
    'DataFrame'         : df,
    'data_source'       : '/datsource/external_df',
      '_optional_info'    : {
        'description'   : 'description of the dataset',
        'keyword'       : 'keyword of dataset Dataframe'
    }
}
)
